from enum import Enum


class FileTypeEnum(str, Enum):
    PROFILE = "PROFILE"
    CITIZENSHIP_FRONT = "CITIZENSHIP_FRONT"
    CITIZENSHIP_BACK = "CITIZENSHIP_BACK"
    MISTRI_CERTIFICATE = "MISTRI_CERTIFICATE"
    OTHER = "OTHER"
