"""add_professional_applications_and_update_profiles

Revision ID: 075ae3218523
Revises: cdd5cc7cdff0
Create Date: 2026-07-29 12:31:42.616884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075ae3218523'
down_revision: Union[str, Sequence[str], None] = 'cdd5cc7cdff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to existing Postgres file_type_enum if needed
    op.execute("ALTER TYPE file_type_enum ADD VALUE IF NOT EXISTS 'Profile';")
    op.execute("ALTER TYPE file_type_enum ADD VALUE IF NOT EXISTS 'Citizenship Front';")
    op.execute("ALTER TYPE file_type_enum ADD VALUE IF NOT EXISTS 'Citizenship Back';")
    op.execute("ALTER TYPE file_type_enum ADD VALUE IF NOT EXISTS 'Certificate';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('professional_applications',
    sa.Column('professional_application_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.Integer(), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=False),
    sa.Column('about_yourself', sa.Text(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('profile_image_id', sa.String(length=13), nullable=False),
    sa.Column('citizenship_front_id', sa.String(length=13), nullable=False),
    sa.Column('citizenship_back_id', sa.String(length=13), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='application_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=13), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizenship_back_id'], ['file.file_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['citizenship_front_id'], ['file.file_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_image_id'], ['file.file_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_application_id')
    )
    op.create_index(op.f('ix_professional_applications_professional_application_id'), 'professional_applications', ['professional_application_id'], unique=False)
    op.create_index(op.f('ix_professional_applications_user_id'), 'professional_applications', ['user_id'], unique=True)
    op.create_table('professional_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=13), nullable=False),
    sa.Column('profile_image_id', sa.String(length=13), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('about_yourself', sa.Text(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('total_completed_jobs', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_image_id'], ['file.file_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_profiles_id'), 'professional_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_professional_profiles_is_available'), 'professional_profiles', ['is_available'], unique=False)
    op.create_index(op.f('ix_professional_profiles_latitude'), 'professional_profiles', ['latitude'], unique=False)
    op.create_index(op.f('ix_professional_profiles_longitude'), 'professional_profiles', ['longitude'], unique=False)
    op.create_index(op.f('ix_professional_profiles_user_id'), 'professional_profiles', ['user_id'], unique=True)
    op.create_table('professional_skills',
    sa.Column('professional_profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_profile_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional_skills')
    op.drop_index(op.f('ix_professional_profiles_user_id'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_longitude'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_latitude'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_is_available'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_id'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    op.drop_index(op.f('ix_professional_applications_user_id'), table_name='professional_applications')
    op.drop_index(op.f('ix_professional_applications_professional_application_id'), table_name='professional_applications')
    op.drop_table('professional_applications')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
