"""Booking model created

Revision ID: 15d809cf3f3a
Revises: 597c8b308314
Create Date: 2026-08-02 14:04:48.843398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '15d809cf3f3a'
down_revision: Union[str, Sequence[str], None] = '597c8b308314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.String(length=13), nullable=False),
    sa.Column('user_id', sa.String(length=13), nullable=False),
    sa.Column('professional_profile_id', sa.String(length=13), nullable=False),
    sa.Column('booking_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_fee', sa.Float(), nullable=False),
    sa.Column('advance_fee', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('due_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('Unpaid', 'Partial', 'Paid', 'Refunded', name='booking_payment_status_enum'), server_default='Unpaid', nullable=False),
    sa.Column('status', sa.Enum('Pending Payment', 'Confirmed', 'In Progress', 'Completed', 'Cancelled', 'Rescheduled', name='booking_status_enum'), server_default='Pending Payment', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_reminded', sa.Boolean(), nullable=False),
    sa.Column('customer_location', JSONB(), nullable=True),
    sa.Column('professional_location', JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.professional_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.create_index(op.f('ix_bookings_professional_profile_id'), 'bookings', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_professional_profile_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
