"""add_application_skills_and_other_skills

Revision ID: 1e8d175a37f8
Revises: 20f715a37166
Create Date: 2026-07-29 15:37:26.383013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8d175a37f8'
down_revision: Union[str, Sequence[str], None] = '20f715a37166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_skills',
    sa.Column('professional_application_id', sa.String(length=13), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_application_id'], ['professional_applications.professional_application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_application_id', 'skill_id')
    )
    op.add_column('professional_applications', sa.Column('other_skills', sa.Text(), nullable=True))
    op.add_column('professional_profiles', sa.Column('other_skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional_profiles', 'other_skills')
    op.drop_column('professional_applications', 'other_skills')
    op.drop_table('application_skills')
    # ### end Alembic commands ###
