"""add booking payment review migration

Revision ID: 6241d670eb8e
Revises: 15d809cf3f3a
Create Date: 2026-08-09 10:58:05.534450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6241d670eb8e'
down_revision: Union[str, Sequence[str], None] = '15d809cf3f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=20), nullable=False),
    sa.Column('booking_id', sa.String(length=13), nullable=False),
    sa.Column('user_id', sa.String(length=13), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('Khalti', 'Esewa', 'Cash', name='payment_method_enum'), nullable=False),
    sa.Column('payment_type', sa.Enum('Booking Advance', 'Booking Complete', 'Booking Cancel', name='payment_type_enum'), nullable=False),
    sa.Column('gateway_reference_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Success', 'Failed', name='payment_transaction_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=13), nullable=False),
    sa.Column('booking_id', sa.String(length=13), nullable=False),
    sa.Column('reviewer_id', sa.String(length=13), nullable=False),
    sa.Column('professional_profile_id', sa.String(length=13), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_profile_id'], ['professional_profiles.professional_profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_reviews_professional_profile_id'), 'reviews', ['professional_profile_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_professional_profile_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
