"""add_citizenship_files_to_professional_profiles

Revision ID: 829818b1b02e
Revises: 1e8d175a37f8
Create Date: 2026-07-31 16:41:08.560642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829818b1b02e'
down_revision: Union[str, Sequence[str], None] = '1e8d175a37f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_profiles', sa.Column('citizenship_front_id', sa.String(length=13), nullable=False))
    op.add_column('professional_profiles', sa.Column('citizenship_back_id', sa.String(length=13), nullable=False))
    op.alter_column('professional_profiles', 'experience',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'professional_profiles', 'file', ['citizenship_back_id'], ['file_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'professional_profiles', 'file', ['citizenship_front_id'], ['file_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professional_profiles', type_='foreignkey')
    op.drop_constraint(None, 'professional_profiles', type_='foreignkey')
    op.alter_column('professional_profiles', 'experience',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('professional_profiles', 'citizenship_back_id')
    op.drop_column('professional_profiles', 'citizenship_front_id')
    # ### end Alembic commands ###
