"""Migration for make sure professional_skills is outside typechecking

Revision ID: cdd5cc7cdff0
Revises: de5671bd7f0e
Create Date: 2026-06-16 08:33:49.415643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd5cc7cdff0'
down_revision: Union[str, Sequence[str], None] = 'de5671bd7f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
