"""Migration on jestha 2 after pull from abhishek

Revision ID: de5671bd7f0e
Revises: e19338c9bf02
Create Date: 2026-06-16 08:13:07.599628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5671bd7f0e'
down_revision: Union[str, Sequence[str], None] = 'e19338c9bf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
