"""File models added

Revision ID: e19338c9bf02
Revises: 93b200f9f184
Create Date: 2026-05-03 20:39:42.262116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19338c9bf02'
down_revision: Union[str, Sequence[str], None] = '93b200f9f184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.String(length=13), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('meta_type', sa.Enum('image', 'video', 'pdf', name='file_meta_type_enum'), nullable=False),
    sa.Column('file_type', sa.Enum('PROFILE', 'MISTRI_CERTIFICATE', 'OTHER', name='file_type_enum'), nullable=False),
    sa.Column('user_id', sa.String(length=13), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_file_file_id'), 'file', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_file_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
